version: "0.2"
ignorePaths:
  - .git
  - .gitignore
  - bun.lockb
  - "**/generated"
  - "**/prisma/migrations"
dictionaryDefinitions: []
dictionaries: []
words:
  - anthropics
  - Auggie
  - AUGGIE
  - auggie
  - Avenir
  - Bluch
  - bunx
  - chax-at
  - clippy
  - DBNAME
  - Dockerfiles
  - dotenvx
  - Entra
  - evenodd
  - Groot
  - initialised
  - msie
  - Msal
  - mydb
  - neverthrow
  - pycache
  - Qwen
  - QWEN
  - qwen
  - tfstate
  - TXXX
  - uvx
  - venv
  - VITE
ignoreWords: []
import: []
