version: "0.2"
ignorePaths:
  - .git
  - .gitignore
  - bun.lockb
  - "**/generated"
  - "**/prisma/migrations"
dictionaryDefinitions: []
dictionaries: []
words:
  - anthropics
  - bunx
  - chax-at
  - DBNAME
  - Dockerfiles
  - dotenvx
  - Entra
  - Msal
  - mydb
  - neverthrow
  - uvx
  - venv
  - VITE
ignoreWords: []
import: []
