version: "0.2"
ignorePaths:
  - .git
  - .gitignore
  - bun.lockb
  - "**/generated"
  - "**/prisma/migrations"
dictionaryDefinitions: []
dictionaries: []
words:
  - anthropics
  - auggie
  - Auggie
  - AUGGIE
  - Avenir
  - Bluch
  - bunx
  - chax-at
  - clippy
  - DBNAME
  - Dockerfiles
  - dotenvx
  - Entra
  - evenodd
  - Groot
  - initialised
  - Msal
  - msie
  - mydb
  - neverthrow
  - pycache
  - qwen
  - Qwen
  - QWEN
  - tfstate
  - TXXX
  - uvx
  - venv
  - VITE
  - worktree
  - worktrees
  - automations
  - netcat
  - ncat
  - fdisk
  - gdisk
  - pkill
  - nftables
  - sato
  - Sato
  - tanaka
  - Tanaka
  - kato
  - Kato
  - ichiro
  - Ichiro
  - jiro
  - Jiro
  - kenta
  - Kenta
  - yosuke
  - Yosuke
ignoreWords: []
import: []
